spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false


server:
  tomcat:
    uri-encoding: utf-8
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 512
    default-statement-timeout: 30


